import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const osvaldito = Oswald({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-osvaldito',
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={osvaldito.className}>{children}</body>
    </html>
  );
}
